# .air.toml

# Root directory for Air to watch
root = "."

# Temporary directory for build artifacts
tmp_dir = "tmp"

[build]
  # Command to build the application, disabling VCS stamping
  cmd = "go build -buildvcs=false -o tmp/main ./cmd/api"

  # Binary output path
  bin = "tmp/main"

  # File extensions to watch for changes
  include_ext = ["go", "tpl", "tmpl", "html"]

  # Directories to exclude from watching
  exclude_dir = ["assets", "tmp", "vendor"]

  # Enable polling to detect file changes
  poll = true
  interval = 1000  # Polling interval in milliseconds

[log]
  # Enable timestamp in logs
  time = true

[color]
  # Color settings for different components
  main = "yellow"
  watcher = "cyan"
  build = "green"
  runner = "magenta"

[env]
  # Environment variables
  APP_ENV = "development"
  # Add other environment variables as needed
