root = "."
tmp_dir = "tmp"

[build]
  # Be explicit about the entry point and force rebuild
  main = "./cmd/api"
  cmd = "go clean -cache && go build -buildvcs=false -a -gcflags='all=-N -l' -o ./tmp/main ./cmd/api"
  bin = "./tmp/main"

  # More aggressive watching settings
  delay = 0
  poll = true
  poll_interval = 500

  # Watch Go files
  include_ext = ["go"]
  exclude_dir = ["tmp", "vendor", ".git"]
  follow_symlink = true

  # Full rebuild
  full_bin = "APP_ENV=dev go run ./cmd/api/main.go"
  rerun = true
  rerun_delay = 500

[log]
  time = true
  main_only = false

[screen]
  clear_on_rebuild = true

[misc]
  clean_on_exit = true