prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    retention: 7d
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 1Gi
  service:
    type: NodePort
    nodePort: 30090

grafana:
  adminPassword: admin
  service:
    type: NodePort
    nodePort: 30091
  persistence:
    enabled: true
    size: 1Gi

alertmanager:
  enabled: true
  service:
    type: NodePort
    nodePort: 30093