apiVersion: v1
kind: ConfigMap
metadata:
  name: maintenance-api-config
  namespace: maintenance-api
  labels:
    app.kubernetes.io/name: maintenance-api
    app.kubernetes.io/component: config
data:
  APP_PORT_HOST: "8080"
  DB_HOST: "mysql"
  DB_NAME: "tasks_db"
  DB_USER: "user"
  MYSQL_PORT_CONTAINER: "3306"
  LOG_LEVEL: "info"
  METRICS_ENABLED: "true"