apiVersion: v1
kind: Secret
metadata:
  name: ghcr-secret
  namespace: maintenance-api
  labels:
    app.kubernetes.io/name: maintenance-api
    app.kubernetes.io/component: registry
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7InVzZXJuYW1lIjoibWFrY2ltMzkyIiwicGFzc3dvcmQiOiJHSF9UT0tFTl9IRVJFIn19fQ==
# Note: Replace GH_TOKEN_HERE with your actual GitHub token
# To create this secret, run:
# kubectl create secret docker-registry ghcr-secret \
#   --docker-server=ghcr.io \
#   --docker-username=makcim392 \
#   --docker-password=YOUR_GITHUB_TOKEN \
#   --namespace=maintenance-api