apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init
  namespace: maintenance-api
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/component: init
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS tasks_db;
    USE tasks_db;

    CREATE TABLE IF NOT EXISTS users (
        id VARCHAR(36) PRIMARY KEY,
        username VARCHAR(50) UNIQUE NOT NULL,
        password_hash VARCHAR(255) NOT NULL,
        role ENUM('technician', 'manager') NOT NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS tasks (
        id VARCHAR(36) PRIMARY KEY,
        summary TEXT NOT NULL,
        performed_at TIMESTAMP NOT NULL,
        user_id VARCHAR(36) NOT NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
    );

    -- Insert test data
    INSERT IGNORE INTO users (id, username, password_hash, role) VALUES
    ('a1b2c3d4-e5f6-7890-abcd-123456789012', 'manager1', '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'manager'),
    ('b2c3d4e5-f6g7-8901-bcde-234567890123', 'john_tech', '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'technician'),
    ('c3d4e5f6-g7h8-9012-cdef-345678901234', 'sarah_manager', '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'manager'),
    ('d4e5f6g7-h8i9-0123-def0-456789012345', 'makcim', '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'technician');

    INSERT IGNORE INTO tasks (id, summary, performed_at, user_id) VALUES
    ('e5f6g7h8-i9j0-1234-ef01-567890123456', 'Fixed HVAC system in building A', '2024-12-29 09:00:00', 'b2c3d4e5-f6g7-8901-bcde-234567890123'),
    ('f6g7h8i9-j0k1-2345-f012-678901234567', 'Replaced light bulbs in office 201', '2024-12-29 10:30:00', 'd4e5f6g7-h8i9-0123-def0-456789012345'),
    ('g7h8i9j0-k1l2-3456-0123-789012345678', 'Scheduled maintenance for elevator 1', '2024-12-29 14:00:00', 'b2c3d4e5-f6g7-8901-bcde-234567890123');