apiVersion: v1
kind: Secret
metadata:
  name: maintenance-api-secrets
  namespace: maintenance-api
  labels:
    app.kubernetes.io/name: maintenance-api
    app.kubernetes.io/component: secret
type: Opaque
stringData:
  DB_PASSWORD: "password"
  JWT_SECRET: "your-secret-key-change-this-in-production"
  MYSQL_ROOT_PASSWORD: "your_secure_root_password"