apiVersion: v1
kind: Secret
metadata:
  name: {{ include "maintenance-api.fullname" . }}-secrets
  labels:
    {{- include "maintenance-api.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_PASSWORD: {{ .Values.secrets.dbPassword | quote }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
  MYSQL_ROOT_PASSWORD: {{ .Values.secrets.mysqlRootPassword | quote }}